from __future__ import annotations

from datetime import datetime

import markdown

from src.common.constants import settings
from src.common.models import EmailDraft, PulseNote

HTML_WRAPPER = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         line-height: 1.6; color: #1a1a1a; max-width: 640px; margin: 0 auto; padding: 24px; }}
  h1 {{ color: #00d09c; font-size: 22px; border-bottom: 2px solid #00d09c; padding-bottom: 8px; }}
  h2 {{ color: #44475b; font-size: 17px; margin-top: 24px; }}
  blockquote {{ border-left: 3px solid #00d09c; margin: 12px 0; padding: 8px 16px;
                background: #f8f9fa; font-style: italic; }}
  li {{ margin-bottom: 8px; }}
  strong {{ color: #44475b; }}
  .greeting {{ font-size: 15px; margin-bottom: 16px; }}
  .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #e0e0e0;
             font-size: 12px; color: #888; }}
</style>
</head>
<body>
{greeting}
{body}
<div class="footer">
  Generated by GROWW App Review Analyser &middot; {timestamp}
</div>
</body>
</html>"""


def build_subject(note: PulseNote) -> str:
    return (
        f"GROWW Weekly Review Pulse -- Week of {note.report_date} "
        f"| Avg {note.average_rating}/5 | {note.total_reviews} reviews"
    )


def compose_email(
    note: PulseNote,
    recipient: str,
    recipient_name: str | None = None,
) -> EmailDraft:
    """
    Build a multipart email draft (plain-text + HTML) from a PulseNote.

    recipient: provided by the frontend/caller at runtime (required).
    recipient_name: if provided, adds "Hi {name}," greeting.
    """
    to = recipient

    greeting_plain = ""
    greeting_html = ""
    if recipient_name:
        greeting_plain = f"Hi {recipient_name},\n\n"
        greeting_html = f'<p class="greeting">Hi {recipient_name},</p>'

    plain_body = greeting_plain + note.plaintext_content

    html_inner = markdown.markdown(
        note.markdown_content,
        extensions=["extra"],
    )

    html_body = HTML_WRAPPER.format(
        greeting=greeting_html,
        body=html_inner,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
    )

    subject = build_subject(note)

    return EmailDraft(
        to=to,
        subject=subject,
        html_body=html_body,
        plain_body=plain_body,
        generated_at=datetime.now().isoformat(),
        report_date=note.report_date,
    )
